// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// TwotailedGSEA
RcppExport SEXP TwotailedGSEA(SEXP regulon, SEXP tvalue, SEXP min, SEXP max, SEXP nPerm);
RcppExport SEXP _RegSeq_TwotailedGSEA(SEXP regulonSEXP, SEXP tvalueSEXP, SEXP minSEXP, SEXP maxSEXP, SEXP nPermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regulon(regulonSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tvalue(tvalueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min(minSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max(maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nPerm(nPermSEXP);
    rcpp_result_gen = Rcpp::wrap(TwotailedGSEA(regulon, tvalue, min, max, nPerm));
    return rcpp_result_gen;
END_RCPP
}
// OnetailedGSEA
RcppExport SEXP OnetailedGSEA(SEXP regulon, SEXP tvalue, SEXP min, SEXP max, SEXP nPerm);
RcppExport SEXP _RegSeq_OnetailedGSEA(SEXP regulonSEXP, SEXP tvalueSEXP, SEXP minSEXP, SEXP maxSEXP, SEXP nPermSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type regulon(regulonSEXP);
    Rcpp::traits::input_parameter< SEXP >::type tvalue(tvalueSEXP);
    Rcpp::traits::input_parameter< SEXP >::type min(minSEXP);
    Rcpp::traits::input_parameter< SEXP >::type max(maxSEXP);
    Rcpp::traits::input_parameter< SEXP >::type nPerm(nPermSEXP);
    rcpp_result_gen = Rcpp::wrap(OnetailedGSEA(regulon, tvalue, min, max, nPerm));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP OnetailedGSEA(SEXP, SEXP, SEXP, SEXP, SEXP);
RcppExport SEXP TwotailedGSEA(SEXP, SEXP, SEXP, SEXP, SEXP);

static const R_CallMethodDef CallEntries[] = {
    {"_RegSeq_TwotailedGSEA", (DL_FUNC) &_RegSeq_TwotailedGSEA, 5},
    {"_RegSeq_OnetailedGSEA", (DL_FUNC) &_RegSeq_OnetailedGSEA, 5},
    {"OnetailedGSEA",         (DL_FUNC) &OnetailedGSEA,         5},
    {"TwotailedGSEA",         (DL_FUNC) &TwotailedGSEA,         5},
    {NULL, NULL, 0}
};

RcppExport void R_init_RegSeq(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
