# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

TwotailedGSEA <- function(regulon, tvalue, min, max, nPerm) {
    .Call('_RegSeq_TwotailedGSEA', PACKAGE = 'RegSeq', regulon, tvalue, min, max, nPerm)
}

OnetailedGSEA <- function(regulon, tvalue, min, max, nPerm) {
    .Call('_RegSeq_OnetailedGSEA', PACKAGE = 'RegSeq', regulon, tvalue, min, max, nPerm)
}

